
char* ananasTab[5]={
"                         `                        \n"
"                      `osd-                       \n"
"           `+/-`     :y- :y     `                 \n"
"           s+.:oo+` -h`   m`/oood                 \n"
"           d.   `-s+y:    ds-` ++                 \n"
"           d-      /N.    `   `d`                 \n"
"           +s       `        `y-                  \n"
"    .://////m-              -y:                   \n"
"  +s+-...`...`        `.://sdo//:.                \n"
"  :y+.             ./sdyo+sd///+oyhs:`            \n"
"   `-oo/-.`     `:s+-------N--------:d+`          \n"
"      `/yhs-   -syy        d-        d+o+`        \n"
"     -o+-`    +s..h        s/        o+ :s/       \n"
"    oo.      oh:::N/:::::::sh::::::::sh::/hy`     \n"
"   oy....-::od....h:.--.-..:m--------:m----/y.    \n"
"   ://///::-so    o/        d.        m`    -h`   \n"
"            y:    :s        s/        y:     /y   \n"
"            y/````.d  ``````/y        s+      h-  \n"
"            +d++++oNo+oooo+ooN+++++++/yh++++++ho  \n"
"            `d`    h.        m`       -h      /y  \n"
"             +s    s/        y:       `m      +o  \n"
"              y/   /o        /s        N`     h-  \n"
"              `h/../h````````:d````````d-````:y   \n"
"               `yh+/N//++////+mo+++++++myooosh.   \n"
"                 +y-d`        y:       s/ `/s`    \n"
"                  `+m/        +s       oo+s:      \n"
"                    `/s+-`    -h    `:+so-        \n"
"                       `:+++++om+o+++:`           \n"
"                                                  \n"

,

"                  ++:         -+o                 \n"
"                 so`:so`   `oo:`m`                \n"
"                :h    -y: /y.  `m                 \n"
"                s/     `hsy`   /h/+++s/           \n"
"      .:///+/:. y:      -d`    ++.``-h`           \n"
"     `d+````.-/+h/       `         :y`            \n"
"      .yo`      ``               .o+`             \n"
"       `:s/.             `...``:+o.               \n"
"        `:sds:     .:/+ohhso+yyys+:`              \n"
"     `/o+:-..`  `:ohy.``..:/+ms+//+so-            \n"
"    /s-`      `+o:`y:       `m`..-:+sho.          \n"
"   `yo//:--..:yy/::m.       /s       `+d:         \n"
"     `.--://od.``.oy/+++/:-.y/        s+s+        \n"
"           `d-    y-   `.-:/No+/:-.`  d. s+       \n"
"           oo     d        -h `.-://+sm:--h/      \n"
"           m+-.``-y        +o        so-:/om`     \n"
"          `N-:/+ods:-..`   h-        d.    oo     \n"
"          `m    `d.-:/+oo++m.``     .d     `m     \n"
"           m`   :s       `oh//+++/-.so      m`    \n"
"           s/   y-        y/    `.-:N+++/:-.m`    \n"
"           :d/-.m`        m`       :h   `-:oh     \n"
"            ys/yh+o+:.`` -h        y/      y/     \n"
"            `h:y-  .-//+ohy:.``   `m      /s      \n"
"             `ym`        h/:/++o+:ss``   /s       \n"
"               os`      `N      `-N+oooos+        \n"
"                .oo.    /y       :y  -oo.         \n"
"                  `/o+/-h/     `.hsoo/`           \n"
"                      .:/+++++++/-.               \n"

,

"                                                  \n"
"                       `oss:                      \n"
"                      -h:  +s       `-:           \n"
"          `-::-.     .d.    /y  `+oo/:m`          \n"
"          -m---/oo+. h:      d:oo.`  oo           \n"
"           so    `.+sd       sd-    /y``          \n"
"           `so      `.       .`    .ys+++sy`      \n"
"          `.-sh-                    `  `/s-       \n"
"      `:+o+///+o-                    ./o:`        \n"
"     -d+.         `-/+s+ooyho+//--:/++.`          \n"
"     `-oo/:.   `/o+:-h/` `.:oo+syoh+.             \n"
"        `.:+oosooo/.o+       `+ds+:/s+`           \n"
"            :y:  `-hh+-`     .h. .:+oyh`          \n"
"           +s`    /o`.:++:. `h-     `-oh`         \n"
"          +h.    :s`    `-/odo`       `ds         \n"
"         .d/o+:.-y`        y+/o+:.   `y:y-        \n"
"         y/  ./yd+.`      +s   .:+o/.s+ -h        \n"
"        `m    .y-:+o+-`  :y`      `-dh+-.m`       \n"
"        :y   `y-    -/oo+d.        +s ./om:       \n"
"        +y. `y-        -mo+/.`    /y`    y:       \n"
"        +hosh+`       `h-  -/o+-`/y`     d-       \n"
"        -d s++o+-`    y/      `:sm+.`   `m        \n"
"         hy+   ./o+:`oo        -h.-/o+-`o+        \n"
"         .m`      `:hm/`      -h.    ./hy         \n"
"          /y`      :h`:oo/.  -d.      /y`         \n"
"           -y-    .d.    -+ood.     .s+           \n"
"            `+s-`.h.       -d+so:`.os.            \n"
"               :ohs-`     -h`  -ydo.              \n"
"                  .:++++++ds+++/.                 \n"

,

"                               ./`                \n"
"                -o+:.       `/s+:h-               \n"
"                +s`./so`   :y:`  -d               \n"
"                :h    .oo`+s`     h:    ...`      \n"
"                 d-     -hs       y/:+o+///ho     \n"
"         `-//////od.     ``      `Ns:`   `oo`     \n"
"        `do.````.-os              -     :y:       \n"
"         .ss-                          -so+++:`   \n"
"           .oo/. `-///++ho+//:-`           .+y/   \n"
"             `/hy+ss-`-s/```:yhoo/.   `.:/o+-`    \n"
"            .oo:`  -sss.     `:s+syyh+//-.`       \n"
"          `oo-     :s/s/`      -dh+-oo`           \n"
"         .yys.   .o+` `:s/`  `+s-`:s/+y`          \n"
"        -y. -s+./o-     `:o+:s/    `:sdo          \n"
"       .h.    ohy.        .hd+`      `/m`         \n"
"      `h-   .o+.:s+.     :y:`/s/`    `+N.         \n"
"      od` `/o-    :y+. .oo`   `/s/` -s/h-         \n"
"     `m/s+s/        :yoy-       `/yss` h-         \n"
"     -d`oys:`       .sos:`       /y+s/`m`         \n"
"     -ms- `+y:    `+s. `:s/`   -s+` `/yd          \n"
"     .m     `+o-`-s+      /o:.os.     h:          \n"
"      d.      `shh.        `yds`     /y           \n"
"      :y      -y/so.      -y+`/s:`  -h`           \n"
"       +s`  `os`  -s+`  .so`    /s//y`            \n"
"        -y//y-      -y+os-       -d/              \n"
"          :y+.       /hh+`    `:so`               \n"
"            .+oo:. :y:  /h+./oo:                  \n"
"                -/+yoo++++s/.                     \n"

,

"                                                  \n"
"                       .                          \n"
"                      /hoo/`                      \n"
"                      h/ `:y:     ./o+ss          \n"
"                      m.   `s+  /s+-`  d.         \n"
"             so+++++:.d.    `ssy/`     h-         \n"
"             +h` ```-ods     `+`      `d`         \n"
"              +y.     .:             `yy/+++++//- \n"
"               -s+`                  :s:.`````:y/ \n"
"               `-shosy+o++oo/-`            ./o+.  \n"
"            `:+o/-.``s/`:+o:./ss:`        /hs/`   \n"
"          .+ho`      :hh:`    `yhoo.       `.-oo. \n"
"        .+o--h:   ./o/.oo`     `oo/d+--...--:/+s/ \n"
"       /s-   .h/:+/.    /s`    `:dd:sd::/::--.`   \n"
"     `s+`   `:ohs`       :y.`-+o:./y.s+           \n"
"    .hm. `-++:``so`       :dy/.    :y:m           \n"
"    h:/d+o:`     os`   `:oo:y:      .yN`          \n"
"   +h/++h-        /y..+o/`  .y/      -N`          \n"
"  `d+-  -h-       .sds.      `s+  `-+hy           \n"
"  -h     .h-   `:oo:-y.        os/o+.h-           \n"
"  -y      `y/-+o/`   .y:     `/osh. /y            \n"
"  `d      `/mh.       `s/ `:oo:` :h:h`            \n"
"   o+  `-oo:.y+        `yyo/`     +m.             \n"
"    s++o/.    s+    `.oo/os`     :h.              \n"
"     +h.       oo`-+o/.   /y`  .so`               \n"
"      .s+.     -dm+.       -h-oo.                 \n"
"        .oo:-oo/`+h`      .+y+.                   \n"
"           -soo/:-+d-:/oo+/.                      \n"
"               `-::::-`                           \n"

};